# Generated by Django 4.1.2 on 2022-11-07 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=200)),
                ('password', models.CharField(max_length=200)),
                ('name', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200)),
                ('phoneNumber', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=200)),
                ('isCompany', models.BooleanField()),
                ('isEmployee', models.BooleanField()),
                ('isAdmin', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Recruitment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idCompany', models.IntegerField()),
                ('job', models.CharField(max_length=200)),
                ('salary', models.CharField(max_length=200)),
                ('time', models.CharField(max_length=200)),
                ('desciption', models.CharField(max_length=200)),
                ('tag', models.CharField(max_length=200)),
                ('isApproved', models.BooleanField()),
            ],
        ),
    ]
