# Generated by Django 4.1.2 on 2022-11-07 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0002_account_recruitment'),
    ]

    operations = [
        migrations.CreateModel(
            name='CV',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idAccount', models.IntegerField()),
                ('idRecruitment', models.IntegerField()),
                ('file', models.BinaryField()),
            ],
        ),
        migrations.RemoveField(
            model_name='recruitment',
            name='desciption',
        ),
        migrations.AddField(
            model_name='recruitment',
            name='description',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='account',
            name='address',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='account',
            name='email',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='account',
            name='isAdmin',
            field=models.BooleanField(blank=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='isCompany',
            field=models.BooleanField(blank=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='isEmployee',
            field=models.BooleanField(blank=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='account',
            name='phoneNumber',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='recruitment',
            name='isApproved',
            field=models.BooleanField(blank=True),
        ),
        migrations.AlterField(
            model_name='recruitment',
            name='tag',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
