# Generated by Django 4.1.2 on 2022-11-07 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0003_cv_remove_recruitment_desciption_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cv',
            name='file',
            field=models.FileField(upload_to='spec'),
        ),
    ]
