# Generated by Django 4.1.2 on 2022-11-08 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0004_alter_cv_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='isAdmin',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='account',
            name='isCompany',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='account',
            name='isEmployee',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
