# Generated by Django 4.1.2 on 2022-11-08 03:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0005_alter_account_isadmin_alter_account_iscompany_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Drink',
        ),
    ]
