# Generated by Django 4.1.2 on 2022-11-19 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0006_delete_drink'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recruitment',
            name='job',
            field=models.CharField(choices=[('computer_scientist', 'Computer Scientist'), ('it_professional', 'IT Professional'), ('ux_designer_ui_developer', 'UX Designer & UI Developer'), ('sql_developer', 'SQL Developer'), ('web_designer', 'Web Designer'), ('web_developer', 'Web Developer'), ('help_desk_worker', 'Help Desk Worker'), ('software_engineer', 'Software Engineer'), ('data_entry', 'Data Entry'), ('devops_engineer', 'DevOps Engineer'), ('computer_programmer', 'Computer Programmer'), ('network_administrator', 'Network Administrator'), ('information_security_analyst', 'Information Security Analyst'), ('artificial_intelligence_engineer', 'Artificial Intelligence Engineer'), ('cloud_architect', 'Cloud Architect'), ('it_manager', 'IT Manager'), ('technical_specialist', 'Technical Specialist'), ('application_developer', 'Application Developer'), ('cto', 'Chief Technology Officer (CTO)'), ('cio', 'Chief Information Officer (CIO)')], default='Computer Scientist', max_length=200),
        ),
        migrations.AlterField(
            model_name='recruitment',
            name='salary',
            field=models.CharField(choices=[('1', 'under 10 million'), ('2', '10 to 20 million'), ('3', '20 to 30 million'), ('4', 'below 30 million')], default='1', max_length=200),
        ),
    ]
