# Generated by Django 4.1.3 on 2022-11-27 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0007_alter_recruitment_job_alter_recruitment_salary'),
    ]

    operations = [
        migrations.AddField(
            model_name='cv',
            name='test',
            field=models.CharField(blank=True, max_length=100000),
        ),
        migrations.AlterField(
            model_name='recruitment',
            name='job',
            field=models.CharField(choices=[('Computer Scientist', 'Computer Scientist'), ('IT Professional', 'IT Professional'), ('UX Designer & UI Developer', 'UX Designer & UI Developer'), ('SQL Developer', 'SQL Developer'), ('Web Designer', 'Web Designer'), ('Web Developer', 'Web Developer'), ('Help Desk Worker', 'Help Desk Worker'), ('Software Engineer', 'Software Engineer'), ('Data Entry', 'Data Entry'), ('DevOps Engineer', 'DevOps Engineer'), ('Computer Programmer', 'Computer Programmer'), ('Network Administrator', 'Network Administrator'), ('Information Security Analyst', 'Information Security Analyst'), ('Artificial Intelligence Engineer', 'Artificial Intelligence Engineer'), ('Cloud Architect', 'Cloud Architect'), ('IT Manager', 'IT Manager'), ('Technical Specialist', 'Technical Specialist'), ('Application Developer', 'Application Developer'), ('Chief Technology Officer (CTO)', 'Chief Technology Officer (CTO)'), ('Chief Information Officer (CIO)', 'Chief Information Officer (CIO)')], default='Computer Scientist', max_length=200),
        ),
        migrations.AlterField(
            model_name='recruitment',
            name='salary',
            field=models.CharField(choices=[('under 10 million vnd', 'under 10 million vnd'), ('10 to 20 million vnd', '10 to 20 million vnd'), ('20 to 50 million vnd', '20 to 50 million vnd'), ('above 50 million vnd', 'above 50 million vnd')], default='1', max_length=200),
        ),
    ]
