# Generated by Django 4.1.3 on 2022-11-27 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0008_cv_test_alter_recruitment_job_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cv',
            name='test',
            field=models.CharField(blank=True, max_length=500000),
        ),
    ]
