# Generated by Django 4.1.3 on 2022-11-27 09:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0009_alter_cv_test'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cv',
            old_name='test',
            new_name='data',
        ),
        migrations.RemoveField(
            model_name='cv',
            name='file',
        ),
    ]
